
BLENDER="C:\Program Files\Blender Foundation\Blender 3.6\blender.exe"
DIST=../dist

all : \
    $(DIST)/cube1.pnct \
    $(DIST)/cube1.scene \

$(DIST)/cube1.scene : cube1.blend export-scene.py
    $(BLENDER) --background --python export-scene.py -- "cube1.blend:Main" "$(DIST)/cube1.scene"

$(DIST)/cube1.pnct : cube1.blend export-meshes.py
    $(BLENDER) --background --python export-meshes.py -- "cube1.blend:Main" "$(DIST)/cube1.pnct" 
